const ACTION_LABELS: Record<string, string> = {
  LOGIN: 'Masuk',
  LOGIN_FAILED: 'Gagal masuk',
  LOGOUT: 'Keluar',
  SIGNUP_ADMIN: 'Pendaftaran admin',
  APPROVE_ADMIN: 'Setujui admin',
  CREATE_ADMIN: 'Tambah admin',
  DELETE_ADMIN: 'Hapus admin',
  UPDATE_PROFILE: 'Ubah profil',
  CHANGE_PASSWORD: 'Ganti password',
  EMAIL_CHANGE_REQUEST: 'Permintaan ganti email',
  EMAIL_CHANGE: 'Ganti email',
  RESET_PASSWORD_REQUEST: 'Permintaan reset password',
  RESET_PASSWORD: 'Reset password',
  CREATE: 'Tambah buku',
  UPDATE: 'Ubah buku',
  DELETE: 'Hapus buku',
  DELETE_REQUEST: 'Ajukan hapus buku',
  REJECT_DELETE_REQUEST: 'Tolak pengajuan hapus',
  INVENTORY_CHECK: 'Cek inventaris',
  POSITION_CHANGE: 'Pindah posisi',
  BOOK_STOCK_SPLIT_UPDATE: 'Ubah stok per posisi',
  BOOK_BULK_CATEGORIZE: 'Kategorisasi massal',
  CATEGORY_CREATE: 'Tambah kategori',
  CATEGORY_RENAME: 'Ganti nama kategori',
  CATEGORY_MOVE: 'Pindah kategori',
  CATEGORY_REORDER: 'Urutkan kategori',
  CATEGORY_DELETE: 'Hapus kategori',
  CATEGORY_REQUEST: 'Ajukan kategori',
  APPROVE_CATEGORY_REQUEST: 'Setujui pengajuan kategori',
  REJECT_CATEGORY_REQUEST: 'Tolak pengajuan kategori',
  APPROVE_LOAN_REQUEST: 'Setujui permintaan pinjam',
  REJECT_LOAN_REQUEST: 'Tolak permintaan pinjam',
  RETURN_LOAN: 'Pengembalian buku',
  MAINTENANCE_START: 'Mulai maintenance',
  MAINTENANCE_APPROVE: 'Setujui maintenance',
  MAINTENANCE_REJECT: 'Tolak maintenance',
  MAINTENANCE_END: 'Akhiri maintenance',
}

export function actionLabel(code: string): string {
  return ACTION_LABELS[code] ?? code
}
