/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminBooksIndexRouteImport } from './routes/admin/books/index'
import { Route as AdminBooksCategoryRequestsRouteImport } from './routes/admin/books/category-requests'
import { Route as AdminBooksDeleteRequestsRouteImport } from './routes/admin/books/delete-requests'
import { Route as AdminBooksNewRouteImport } from './routes/admin/books/new'
import { Route as AdminLoansRequestsRouteImport } from './routes/admin/loans/requests'
import { Route as AdminBooksBookIdEditRouteImport } from './routes/admin/books/$bookId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/admin/books/',
  path: '/admin/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksCategoryRequestsRoute =
  AdminBooksCategoryRequestsRouteImport.update({
    id: '/admin/books/category-requests',
    path: '/admin/books/category-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBooksDeleteRequestsRoute =
  AdminBooksDeleteRequestsRouteImport.update({
    id: '/admin/books/delete-requests',
    path: '/admin/books/delete-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminBooksNewRoute = AdminBooksNewRouteImport.update({
  id: '/admin/books/new',
  path: '/admin/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoansRequestsRoute = AdminLoansRequestsRouteImport.update({
  id: '/admin/loans/requests',
  path: '/admin/loans/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksBookIdEditRoute = AdminBooksBookIdEditRouteImport.update({
  id: '/admin/books/$bookId/edit',
  path: '/admin/books/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/approvals'
    | '/admin/login'
    | '/admin/members'
    | '/admin/signup'
    | '/admin/'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books/'
    | '/admin/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/approvals'
    | '/admin/login'
    | '/admin/members'
    | '/admin/signup'
    | '/admin'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books'
    | '/admin/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/approvals'
    | '/admin/login'
    | '/admin/members'
    | '/admin/signup'
    | '/admin/'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books/'
    | '/admin/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBooksCategoryRequestsRoute: typeof AdminBooksCategoryRequestsRoute
  AdminBooksDeleteRequestsRoute: typeof AdminBooksDeleteRequestsRoute
  AdminBooksNewRoute: typeof AdminBooksNewRoute
  AdminLoansRequestsRoute: typeof AdminLoansRequestsRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBooksBookIdEditRoute: typeof AdminBooksBookIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/admin/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/category-requests': {
      id: '/admin/books/category-requests'
      path: '/admin/books/category-requests'
      fullPath: '/admin/books/category-requests'
      preLoaderRoute: typeof AdminBooksCategoryRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/delete-requests': {
      id: '/admin/books/delete-requests'
      path: '/admin/books/delete-requests'
      fullPath: '/admin/books/delete-requests'
      preLoaderRoute: typeof AdminBooksDeleteRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/new': {
      id: '/admin/books/new'
      path: '/admin/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loans/requests': {
      id: '/admin/loans/requests'
      path: '/admin/loans/requests'
      fullPath: '/admin/loans/requests'
      preLoaderRoute: typeof AdminLoansRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/$bookId/edit': {
      id: '/admin/books/$bookId/edit'
      path: '/admin/books/$bookId/edit'
      fullPath: '/admin/books/$bookId/edit'
      preLoaderRoute: typeof AdminBooksBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBooksCategoryRequestsRoute: AdminBooksCategoryRequestsRoute,
  AdminBooksDeleteRequestsRoute: AdminBooksDeleteRequestsRoute,
  AdminBooksNewRoute: AdminBooksNewRoute,
  AdminLoansRequestsRoute: AdminLoansRequestsRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBooksBookIdEditRoute: AdminBooksBookIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
