/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InformasiRouteImport } from './routes/informasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCategorizeRouteImport } from './routes/admin/categorize'
import { Route as AdminConfirmEmailRouteImport } from './routes/admin/confirm-email'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMaintenanceRouteImport } from './routes/admin/maintenance'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminBooksIndexRouteImport } from './routes/admin/books/index'
import { Route as AdminBooksCategoryRequestsRouteImport } from './routes/admin/books/category-requests'
import { Route as AdminBooksDeleteRequestsRouteImport } from './routes/admin/books/delete-requests'
import { Route as AdminBooksNewRouteImport } from './routes/admin/books/new'
import { Route as AdminLoansRequestsRouteImport } from './routes/admin/loans/requests'
import { Route as AdminBooksBookIdEditRouteImport } from './routes/admin/books/$bookId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiRoute = InformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategorizeRoute = AdminCategorizeRouteImport.update({
  id: '/categorize',
  path: '/categorize',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfirmEmailRoute = AdminConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksCategoryRequestsRoute =
  AdminBooksCategoryRequestsRouteImport.update({
    id: '/books/category-requests',
    path: '/books/category-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBooksDeleteRequestsRoute =
  AdminBooksDeleteRequestsRouteImport.update({
    id: '/books/delete-requests',
    path: '/books/delete-requests',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBooksNewRoute = AdminBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRequestsRoute = AdminLoansRequestsRouteImport.update({
  id: '/loans/requests',
  path: '/loans/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksBookIdEditRoute = AdminBooksBookIdEditRouteImport.update({
  id: '/books/$bookId/edit',
  path: '/books/$bookId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/informasi': typeof InformasiRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/categorize': typeof AdminCategorizeRoute
  '/admin/confirm-email': typeof AdminConfirmEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/informasi': typeof InformasiRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/categorize': typeof AdminCategorizeRoute
  '/admin/confirm-email': typeof AdminConfirmEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/informasi': typeof InformasiRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/categorize': typeof AdminCategorizeRoute
  '/admin/confirm-email': typeof AdminConfirmEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/books/category-requests': typeof AdminBooksCategoryRequestsRoute
  '/admin/books/delete-requests': typeof AdminBooksDeleteRequestsRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/loans/requests': typeof AdminLoansRequestsRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$bookId/edit': typeof AdminBooksBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/informasi'
    | '/login'
    | '/maintenance'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/categorize'
    | '/admin/confirm-email'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books/'
    | '/admin/books/$bookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/informasi'
    | '/login'
    | '/maintenance'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/categorize'
    | '/admin/confirm-email'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books'
    | '/admin/books/$bookId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/informasi'
    | '/login'
    | '/maintenance'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/categorize'
    | '/admin/confirm-email'
    | '/admin/forgot-password'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/maintenance'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/reset-password'
    | '/admin/signup'
    | '/admin/'
    | '/admin/books/category-requests'
    | '/admin/books/delete-requests'
    | '/admin/books/new'
    | '/admin/loans/requests'
    | '/admin/books/'
    | '/admin/books/$bookId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InformasiRoute: typeof InformasiRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi': {
      id: '/informasi'
      path: '/informasi'
      fullPath: '/informasi'
      preLoaderRoute: typeof InformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorize': {
      id: '/admin/categorize'
      path: '/categorize'
      fullPath: '/admin/categorize'
      preLoaderRoute: typeof AdminCategorizeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/confirm-email': {
      id: '/admin/confirm-email'
      path: '/confirm-email'
      fullPath: '/admin/confirm-email'
      preLoaderRoute: typeof AdminConfirmEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/category-requests': {
      id: '/admin/books/category-requests'
      path: '/books/category-requests'
      fullPath: '/admin/books/category-requests'
      preLoaderRoute: typeof AdminBooksCategoryRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/delete-requests': {
      id: '/admin/books/delete-requests'
      path: '/books/delete-requests'
      fullPath: '/admin/books/delete-requests'
      preLoaderRoute: typeof AdminBooksDeleteRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/new': {
      id: '/admin/books/new'
      path: '/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminBooksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans/requests': {
      id: '/admin/loans/requests'
      path: '/loans/requests'
      fullPath: '/admin/loans/requests'
      preLoaderRoute: typeof AdminLoansRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books/$bookId/edit': {
      id: '/admin/books/$bookId/edit'
      path: '/books/$bookId/edit'
      fullPath: '/admin/books/$bookId/edit'
      preLoaderRoute: typeof AdminBooksBookIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCategorizeRoute: typeof AdminCategorizeRoute
  AdminConfirmEmailRoute: typeof AdminConfirmEmailRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBooksCategoryRequestsRoute: typeof AdminBooksCategoryRequestsRoute
  AdminBooksDeleteRequestsRoute: typeof AdminBooksDeleteRequestsRoute
  AdminBooksNewRoute: typeof AdminBooksNewRoute
  AdminLoansRequestsRoute: typeof AdminLoansRequestsRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBooksBookIdEditRoute: typeof AdminBooksBookIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCategorizeRoute: AdminCategorizeRoute,
  AdminConfirmEmailRoute: AdminConfirmEmailRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBooksCategoryRequestsRoute: AdminBooksCategoryRequestsRoute,
  AdminBooksDeleteRequestsRoute: AdminBooksDeleteRequestsRoute,
  AdminBooksNewRoute: AdminBooksNewRoute,
  AdminLoansRequestsRoute: AdminLoansRequestsRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBooksBookIdEditRoute: AdminBooksBookIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InformasiRoute: InformasiRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
